### ISSUE TITLE
Help!!!

### ISSUE THREAD

**Issue by SudoPokeMaster** [Adikso/BashBot#12]
I am trying to deploy this bot in heroku but i got this output when i ran python bashbot.py

- 
Traceback (most recent call last):
  File "bot.py", line 3, in <module>
    from bashbot.commands import CommandsManager
  File "/app/bashbot.py", line 5, in <module>
    import bashbot.main
ModuleNotFoundError: No module named 'bashbot.main'; 'bashbot' is not a package
Help me

**Comment by SudoPokeMaster** [comment]
Please help me... my discord tag: Pokemaster#7156

**Comment by Adikso** [comment]
There is updated version of the bot on master branch now. Not all features are available but it should be enough
