### ISSUE TITLE
"$.permission list" isn't working

### ISSUE THREAD

**Issue by AdminRAT** [Adikso/BashBot#2]
When running "$.permission list", the following error spits out
```Ignoring exception in on_message
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/discord/client.py", line 307, in _run_event
    yield from getattr(self, event)(*args, **kwargs)
  File "/home/adminrat/Downloads/BashBot/bashbot/bot.py", line 64, in on_message
    success = await commands_manager.execute(client, message)
  File "/home/adminrat/Downloads/BashBot/bashbot/commands/__init__.py", line 88, in execute
    await command.execute(client, message, alias, args)
  File "/home/adminrat/Downloads/BashBot/bashbot/commands/__init__.py", line 59, in execute
    await getattr(self, action)(client, message, parameters)
AttributeError: 'PermissionCommand' object has no attribute 'list_all'

**Comment by Adikso** [comment]
This command is not implemented yet. Although BashBot is near to be complete it needs finishing touches. I might implement this as you already reminded me of this project. I also fixed bug with executing commands on private chat with bot (Probably due to library api changes).

**Comment by AdminRAT** [comment]
I'm guessing the same to $.controls too
