### ISSUE TITLE
Unable to install using setup.py or installing the dependacies on RaspberryPi

### ISSUE THREAD

**Issue by jll123567** [Adikso/BashBot#3]
When running the command `sudo python setup.py` I get an error about encoding
error text:
```
Processing dependencies for bashbot==1.0
Searching for websockets>=3.1,<4.0
Reading https://pypi.python.org/simple/websockets/
Best match: websockets 3.4
Downloading https://pypi.python.org/packages/4a/e8/acf36f117deeb18c0b6679624fa11                                                                                        b57b0876044f0ce3f34024c3a7b2d95/websockets-3.4.tar.gz#md5=3586aa49a9e6da35759da0                                                                                        92d5c79c18
Processing websockets-3.4.tar.gz
Writing /tmp/easy_install-peGAAr/websockets-3.4/setup.cfg
Running websockets-3.4/setup.py -q bdist_egg --dist-dir /tmp/easy_install-peGAAr                                                                                        /websockets-3.4/egg-dist-tmp-tgvu6J
Traceback (most recent call last):
  File "setup.py", line 17, in <module>
    "bashbot = bashbot.main:main",
  File "/usr/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/usr/lib/python2.7/dist-packages/setuptools/command/install.py", line 67                                                                                        , in run
    self.do_egg_install()
  File "/usr/lib/python2.7/dist-packages/setuptools/command/install.py", line 11                                                                                        7, in do_egg_install
    cmd.run()
  File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", li                                                                                        ne 393, in run
    self.easy_install(spec, not self.no_deps)
  File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", li                                                                                        ne 617, in easy_install
    return self.install_item(None, spec, tmpdir, deps, True)
  File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", li                                                                                        ne 668, in install_item
    self.process_distribution(spec, dist, deps)
  File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", li                                                                                        ne 716, in process_distribution
    [requirement], self.local_index, self.easy_install
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 631, in resolve
    dist = best[req.key] = env.best_match(req, ws, installer)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 874, in best_ma                                                                                        tch
    return self.obtain(req, installer)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 886, in obtain
    return installer(requirement)
  File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", li                                                                                        ne 636, in easy_install
    return self.install_item(spec, dist.location, tmpdir, deps)
  File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", li                                                                                        ne 666, in install_item
    dists = self.install_eggs(spec, download, tmpdir)
  File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", li                                                                                        ne 856, in install_eggs
    return self.build_and_install(setup_script, setup_base)
  File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", li                                                                                        ne 1078, in build_and_install
    self.run_setup(setup_script, setup_base, args)
  File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", li                                                                                        ne 1063, in run_setup
    run_setup(setup_script, args)
  File "/usr/lib/python2.7/dist-packages/setuptools/sandbox.py", line 68, in run                                                                                        _setup
    DirectorySandbox(setup_dir).run(runner)
  File "/usr/lib/python2.7/dist-packages/setuptools/sandbox.py", line 114, in ru                                                                                        n
    return func()
  File "/usr/lib/python2.7/dist-packages/setuptools/sandbox.py", line 67, in run                                                                                        ner
    _execfile(setup_script, ns)
  File "/usr/lib/python2.7/dist-packages/setuptools/sandbox.py", line 43, in _ex                                                                                        ecfile
    exec(code, globals, locals)
  File "/tmp/easy_install-peGAAr/websockets-3.4/setup.py", line 11, in <module>
    license="MIT",
  File "/usr/lib/python2.7/dist-packages/setuptools/sandbox.py", line 243, in _o                                                                                        pen
    return _open(path,mode,*args,**kw)
TypeError: 'encoding' is an invalid keyword argument for this function
```

When not using setup.py I get a different error relating to encoding after installing the dependencies and running `python bashbot.py`

error text
``` 
File "bashbot.py", line 12
SyntaxError: Non-ASCII character '\xe2' in file bashbot.py on line 12, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details
```

**Comment by jll123567** [comment]
It works now!
Thank you very much!
