### ISSUE TITLE
Bash bot permissions file not working

### ISSUE THREAD

**Issue by IIPoliII** [Adikso/BashBot#6]
Hello,
I am trying to setup the permissions for the bot but i can't make it right and python always make me an error at startup here is the permissions i am "trying" to apply for now.
```
{
    "default": {
        "chat.write": true,
        "info.about": false,
        "info.help": true,
        "input.controls.manage": false,
        "input.repeat": false,
        "internal.settings": false,
        "permissions.manage": false,
        "permissions.manage.edit": false,
        "permissions.manage.view": false,
        "session.close": false,
        "session.freeze": false,
        "session.kill": false,
        "session.killall": false,
        "session.list": true,
        "session.move": false,
        "session.open": false,
        "session.rename": false,
        "session.select": false
    }

       "admin": {
        "chat.write": true,
        "info.about": false,
        "info.help": true,
        "input.controls.manage": false,
        "input.repeat": false,
        "internal.settings": false,
        "permissions.manage": false,
        "permissions.manage.edit": false,
        "permissions.manage.view": false,
        "session.close": false,
        "session.freeze": false,
        "session.kill": false,
        "session.killall": false,
        "session.list": true,
        "session.move": false,
        "session.open": false,
        "session.rename": false,
        "session.select": false
    }

}
```
When i try to run it it does this error : 

```
Loaded `/root/.bashbot/settings.json`
Traceback (most recent call last):
  File "/usr/local/bin/bashbot", line 11, in <module>
    load_entry_point('bashbot==1.0', 'console_scripts', 'bashbot')()
  File "/usr/local/lib/python3.6/dist-packages/bashbot-1.0-py3.6.egg/bashbot/main.py", line 7, in main
  File "/usr/local/lib/python3.6/dist-packages/bashbot-1.0-py3.6.egg/bashbot/settings.py", line 65, in copy_default
  File "/usr/local/lib/python3.6/dist-packages/bashbot-1.0-py3.6.egg/bashbot/settings.py", line 27, in load
  File "/usr/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.6/json/decoder.py", line 355, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting ',' delimiter: line 23 column 8 (char 632)
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7f8f8d889a90>


```

**Comment by Adikso** [comment]
```
"default": {
        "chat.write": true,
        ...
        "session.select": false
 }
```

There is comma missing in your configuration after default block.
It should look like this:
```
"default": {
        "chat.write": true,
        ...
        "session.select": false
 },
```

**Comment by IIPoliII** [comment]
Okay thanks
