### ISSUE TITLE
Can't invoke command

### ISSUE THREAD

**Issue by Dezyox** [Adikso/BashBot#8]
Here is the traceback :

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/discord.py-1.2.3-py3.7.egg/discord/client.py", line 270, in _run_event
    await coro(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/bashbot-1.0-py3.7.egg/bashbot/bot.py", line 49, in on_message
    if is_command(message):
  File "/usr/local/lib/python3.7/dist-packages/bashbot-1.0-py3.7.egg/bashbot/bot.py", line 120, in is_command
    if message.channel.is_private:
AttributeError: 'DMChannel' object has no attribute 'is_private'
```

I tried in a channel, and in private message

I don't think I miss something in the installation process...
Cordially

> If you want to talk to me directly from Discord : `Dezyox#3310`

**Comment by Adikso** [comment]
Discord library that I am using changed a lot since I made this bot. Rewritten version of the library is now the default one and everything breaks. I will be rewritting bashbot from scratch in few days

**Comment by Dezyox** [comment]
Uhm... Okay, that's pretty sad :/

**Comment by miiraheart** [comment]
Any updates on this, I'm having the same issue

**Comment by angadkochar** [comment]
I would love to see this bot updated is there any news?

**Comment by Adikso** [comment]
There is updated version of the bot on master branch now. It's not finished but should work fine
